on:
  workflow_call:
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - run: npm install -g pnpm
      - run: pnpm install